Add Validations And Specs To Users, Posts, Comments and Likes Models
sharon-odhiambo/Blog-App-Rails pull request #3
Opened 2022-10-28 20:29 UTC by sharon-odhiambo

In this PR I created Validations and Specs for the BlogApp Models

**Below are the highlights**

Create Validations for Users name and posts counter
Create validations for users post title, likes counter and comments counter
Create unit tests for custom methods on users, posts, likes and comments
Ensure no linter errors

**Cheers and Happy Reviewing!**

2022-10-28 21:08 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @sharon-odhiambo,

Nice job, you are almost there.

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used the correct workflow.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-10-28 21:08 UTC, omar-muhamad commented on spec/models/user_spec.rb
> +      end
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_validations_model_spec.md#:~:text=Add%20unit%20specs%20for%20all%20of%20your%20models%27%20methods%20and%20validations.), Please add a unit test for the `most_recent_posts` method.

2022-10-28 21:08 UTC, Omar-Muhamad commented on spec/models/post_spec.rb
> +    expect(@post).to_not be_valid
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_validations_model_spec.md#:~:text=Add%20unit%20specs%20for%20all%20of%20your%20models%27%20methods%20and%20validations.), Please add a unit test for the `most_recent_comments` method.

2022-10-29 10:10 UTC, sharon-odhiambo commented
Hi @Omar-Muhamad , thanks for the review. I have implemented the changes.

2022-10-29 10:31 UTC, KayLemba approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello  @sharon-odhiambo    , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- [x] Your project is professional 

- [x]  Your repo is professional 




 

- [x] No Linter Errors





Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 10:42 UTC, sharon-odhiambo commented
Hi @KayLemba , thank you for the review.

2022-10-29 10:42 UTC, merged